//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAP_Enlace.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siapgapEntities : DbContext
    {
        public siapgapEntities()
            : base("name=siapgapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_area> t_area { get; set; }
        public DbSet<t_marca> t_marca { get; set; }
        public DbSet<t_nombreequipo> t_nombreequipo { get; set; }
        public DbSet<t_producto> t_producto { get; set; }
        public DbSet<t_proveedor> t_proveedor { get; set; }
        public DbSet<t_so> t_so { get; set; }
        public DbSet<t_tipo> t_tipo { get; set; }
        public DbSet<t_ubicacion> t_ubicacion { get; set; }
        public DbSet<t_usuario> t_usuario { get; set; }
    }
}
